plugins {
    id 'fabric-loom' version '1.10-SNAPSHOT'
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "ParchmentMC"
                url = "https://maven.parchmentmc.org"
            }
        }
        filter {
            includeGroupAndSubgroups("org.parchmentmc")
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                url = "https://maven.terraformersmc.com/releases"
            }
        }
        filter {
            includeGroupAndSubgroups("com.terraformersmc")
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings(loom.layered {
        it.officialMojangMappings()
        it.parchment("org.parchmentmc.data:parchment-${project.parchment_minecraft_version}:${project.parchment_mappings_version}@zip")
    })
    compileOnly(project.project(":common")) {
        transitive = false
    }

    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    // COMPAT
    modCompileOnly("com.terraformersmc:modmenu:${project.mod_menu_version}") {
        transitive = false
    }
    modLocalRuntime("com.terraformersmc:modmenu:${project.mod_menu_version}") {
        transitive = false
    }

    modCompileOnly("me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config}")
    modLocalRuntime("me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config}")
}

publishMods {
    file = tasks.remapJar.archiveFile
    modLoaders.add("fabric")

    var env = System.getenv()

    def gitRepo = getExecOutput(['git', 'remote', 'get-url', 'origin'])
    def gitCommit = getExecOutput(['git', 'log', '-n', '1', '--pretty=tformat:%h'])
    def gitPrevCommit = project.findProperty("git_previous_commit") ?: env["GIT_PREVIOUS_COMMIT"]

    var changelogText = ""

    if (gitCommit && gitPrevCommit) {
        changelogText += getExecOutput(['git', 'log', "--pretty=tformat:- %s [(%h)](${gitRepo}/commit/%h)", '' + gitPrevCommit + '..' + gitCommit])
    }

    // Limit the changelog to 500 characters
    changelogText = changelogText.take(500)

    def uploadDependencies = [
            "fabric-api": true,
            "cloth-config": true
    ]

    if (project.hasProperty('curseforge_id_fabric')) {
        curseforge('curseforgeFabric') {
            platform = "curseforge"
            accessToken = project.findProperty("curse_auth")
            projectId = project.findProperty('curseforge_id_fabric')
            announcementTitle = "Lootr ${rootProject.minecraft_version}-${rootProject.mod_version} for Fabric on CurseForge"
            minecraftVersions.add(project.minecraft_version)
            changelog = changelogText

            uploadDependencies.each { dep, required ->
                if (required) {
                    requires(dep)
                } else {
                    optional(dep)
                }
            }
        }
    }

    if (project.hasProperty('modrinth_id_fabric')) {
        modrinth('modrinthFabric') {
            platform = "modrinth"
            accessToken = project.findProperty("modrinth_auth")
            projectId = project.findProperty('modrinth_id')
            announcementTitle = "Lootr ${rootProject.minecraft_version}-${rootProject.mod_version} for Fabric on Modrinth"
            minecraftVersions.add(project.minecraft_version)
            changelog = changelogText

            dependencies {
                uploadDependencies.each { dep, required ->
                    if (required) {
                        requires(dep)
                    } else {
                        optional(dep)
                    }
                }
            }
        }
    }

    if (project.hasProperty("curse_discord_webhook")) {
         discord {
             webhookUrl = project.findProperty("curse_discord_webhook")
             username = "Lootr Update"
         }
    }
}

loom {
    mods {
        "${mod_id}" {
            // Tell Loom about each source set used by your mod here. This ensures that your mod's classes are properly transformed by Loader.
            sourceSet sourceSets.main
            sourceSet project.project(":common").sourceSets.main
        }
    }

    def awFile = project.file("src/main/resources/${mod_id}.accesswidener")
    if (awFile.exists()) {
        accessWidenerPath.set(awFile)
    }

    mixin {
        useLegacyMixinAp = false
    }

    runs {
        configureEach {
            runDir("run")
            ideConfigGenerated(true)
        }

        client {
            client()
            setConfigName("Fabric Client")

            if (project.hasProperty('mc_uuid')) {
                programArg("--uuid=${project.findProperty('mc_uuid')}")
            }

            if (project.hasProperty('mc_username')) {
                programArg("--username=${project.findProperty('mc_username')}")
            }

            if (project.hasProperty('mc_java_agent_path')) {
                vmArg("-javaagent:${project.findProperty('mc_java_agent_path')}")
            }
        }

        server {
            server()
            setConfigName("Fabric Server")
        }
    }
}

tasks.named("compileJava", JavaCompile) {
    source(project.project(":common").sourceSets.main.allJava)
}

tasks.named("javadoc", Javadoc).configure {
    source(project.project(":common").sourceSets.main.allJava)
}

tasks.named("sourcesJar", Jar) {
    from(project.project(":common").sourceSets.main.allSource)
}

processResources {
    from project.project(":common").sourceSets.main.resources

    from(project(":common").sourceSets["generated"].resources) {
        exclude(".cache")
    }
}
