plugins {
    id "idea"
    id "maven-publish"
    id "me.modmuss50.mod-publish-plugin" version "0.8.4" apply false
    id "net.neoforged.moddev" version "2.0.134" apply false
    id("fabric-loom") version("1.14.7") apply(false)
    id("net.fabricmc.fabric-loom-companion") version("1.14.7")
    id ("org.jetbrains.gradle.plugin.idea-ext") version "1.3"
}

def javaVersion = 21

allprojects {
    version = "${rootProject.minecraft_version}-${rootProject.mod_version}"
    group = rootProject.mod_group_id

    repositories {
        mavenLocal()
        mavenCentral()
        exclusiveContent {
            forRepository {
                maven {
                    url = "https://www.cursemaven.com"
                }
            }
            filter {
                includeGroupAndSubgroups("curse.maven")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    url = "https://api.modrinth.com/maven/"
                }
            }
            filter {
                includeGroupAndSubgroups("maven.modrinth")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    url = "https://maven.blamejared.com"
                }
            }
            filter {
                includeGroupAndSubgroups("mezz.jei")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "TerraformersMC"
                    url = "https://maven.terraformersmc.com/"
                }
            }
            filter {
                includeGroupByRegex("dev\\.emi.*")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    url = "https://maven.shedaniel.me"
                }
            }
            filter {
                includeGroupAndSubgroups("me.shedaniel.cloth")
                includeGroupAndSubgroups("me.shedaniel")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = 'TommyLib'
                    url = 'https://dl.cloudsmith.io/public/thomasglasser/tommylib/maven/'
                }
            }
            filter { includeGroupAndSubgroups "dev.thomasglasser.tommylib" }
        }
    }

    tasks.register('buildAndRelease') {
        dependsOn(tasks.build, tasks.publish)
    }
}

subprojects {
    apply plugin: "java-library"
    apply plugin: "maven-publish"
    apply plugin: "me.modmuss50.mod-publish-plugin"
    project.group = rootProject.group
    project.version = rootProject.version

    base {
        archivesName.set("${rootProject.mod_id}-${name}")
    }

    dependencies {
        compileOnly "org.jetbrains:annotations:${jetbrains_annotations_version}"
        compileOnly("com.google.auto.service:auto-service-annotations:${rootProject.auto_service_version}")
        annotationProcessor("com.google.auto.service:auto-service:${rootProject.auto_service_version}")
    }

    processResources {
        filteringCharset = "UTF-8"

        def expandProps = [
                "version"              : project.version,
                "mod_version"          : project.mod_version,
                "maven_group_id"       : project.mod_group_id,
                "mod_id"               : project.mod_id,
                "mod_display_name"     : project.mod_name,
                "mod_description"      : project.mod_description,
                "sources_url"          : project.sources_url,
                "issues_url"           : project.issues_url,
                "license_url"          : project.license_url,
                "homepage_url"         : project.homepage_url,

                "minecraft_version"    : project.minecraft_version,
                "neoforge_version"     : project.neoforge_version,
                "fabric_loader_version": project.fabric_loader_version,
                "java_version"         : "${javaVersion}",
        ]

        filesMatching(['pack.mcmeta', '*.mod.json', 'META-INF/neoforge.mods.toml']) {
            expand expandProps
        }
        inputs.properties(expandProps)
    }

    java {
        if (JavaVersion.current() < JavaVersion.toVersion(javaVersion)) {
            toolchain {
                languageVersion = JavaLanguageVersion.of(javaVersion)
            }
        } else {
            sourceCompatibility = JavaVersion.toVersion(javaVersion)
            targetCompatibility = JavaVersion.toVersion(javaVersion)
        }

        withSourcesJar()
    }

    javadoc {
        options.tags = ["reason"]
    }

    tasks.withType(JavaCompile).configureEach {
        options.release.set(javaVersion)
    }

    publishing {
        tasks.publish.dependsOn build

        publications {
            "${project.name}"(MavenPublication) {
                artifactId = "${rootProject.mod_id}-${name}"
                artifact jar
                artifact project.sourcesJar {
                    archiveClassifier.set('sources')
                }

                pom {
                    name = 'Lootr'
                    description = 'Friendly loot for everyone.'
                    url = 'https://github.com/LootrMinecraft/Lootr'

                    scm {
                        connection = 'git:https://github.com/LootrMinecraft/Lootr.git'
                        developerConnection = 'git:https://github.com/LootrMinecraft/Lootr.git'
                        url = 'https://github.com/LootrMinecraft/Lootr'
                    }

                    licenses {
                        license {
                            name = 'MIT License'
                            url = 'https://opensource.org/licenses/MIT'
                        }
                    }

                    developers {
                        developer {
                            id = 'noobanidus'
                            name = 'Noobanidus'
                            email = 'noobanidus+spam@gmail.com'
                        }
                    }
                }
            }
        }

        repositories {
            maven {
                url = "file:///" + System.getenv("local_maven")
            }
        }
    }

    tasks.publishMods.mustRunAfter tasks.publish
    tasks.buildAndRelease.dependsOn(tasks.publish).dependsOn(tasks.publishMods)
}

tasks.register("tagVersion") {
    doLast {
        def utils = project.objects.newInstance(ExecUtils)
        def tagName = "mdg-${minecraft_version}-${mod_version}"

        def existing = utils.getExecOutput(["git", "tag", "--list", tagName])
        if (existing == tagName) {
            println "Tag $tagName already exists. Skipping."
            return
        }

        println "Creating git tag $tagName"
        utils.getExecOutput(["git", "tag", tagName])
    }
}