org.gradle.jvmargs=-Xmx4096m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Common
minecraft_version=1.21.9
neoform_version=1.21.9-20250930.151910
parchment_minecraft_version=1.21.9
parchment_mappings_version=2025.10.05

# NeoForge
neoforge_version=21.9.2-beta

# Fabric
fabric_loader_version=0.17.2
fabric_api_version=0.133.14+1.21.9
mod_menu_version=16.0.0-rc.1

# MC dependencies
jetbrains_annotations_version=26.0.1
mixin_version=0.15.4+mixin.0.8.7
mixin_extras_version=0.5.0
asm_version=9.7

## Mod Properties
mod_id=lootr
mod_name=Lootr
mod_version=1.17.30.96
mod_description=Generates unique loot for each player that opens a loot container.
sources_url=https://github.com/LootrMinecraft/Lootr
issues_url=https://github.com/LootrMinecraft/Lootr/issues
license_url=https://github.com/LootrMinecraft/Lootr/blob/HEAD/LICENSE
homepage_url=https://www.curseforge.com/minecraft/mc-mods/lootr

# Publishing
mod_group_id=noobanidus.mods.lootr
curseforge_id_neoforge=361276
curseforge_id_fabric=615106
modrinth_id_neoforge=EltpO5cN
modrinth_id_fabric=EltpO5cN
maven_group=noobanidus.mods.lootr

# Compat Dependencies
mod_menu=16.0.0-rc.1
cloth_config=20.0.148

git_previous_commit=8db84a45d421c940dbb37980e6120a9a4c08b412
