org.gradle.daemon=false
org.gradle.jvmargs=-Xmx6500m
minecraft_version=1.21.5
mod_id=lootr
mod_version=1.13.36.89
maven_group=noobanidus.mods.lootr

fabric_loader_version=0.16.14
fabric_api_version=0.125.0+1.21.5

neoforge_version=21.5.70-beta

version_compat_start=1.21.5
version_compat_stop=1.21.5

# Libraries
mixin_extras=0.4.1

# Compat Dependencies
mod_menu=14.0.0-rc.2
cloth_config=18.0.145
architectury=16.1.4

git_previous_commit=fd063f6d77d223e79305b1580aa5e06852c3344f
