org.gradle.daemon=false
org.gradle.jvmargs=-Xmx6500m
minecraft_version=1.21.4
mod_id=lootr
mod_version=1.12.36.88
maven_group=noobanidus.mods.lootr

fabric_loader_version=0.16.9
fabric_api_version=0.111.0+1.21.4

neoforge_version=21.4.22-beta

version_compat_start=1.21.4
version_compat_stop=1.21.4

# Libraries
mixin_extras=0.4.1

# Compat Dependencies
mod_menu=13.0.0-beta.1
cloth_config=17.0.144
architectury=15.0.1

git_previous_commit=479d6d52633895ce60bebfd2fa28731b49dac0a6
