modLoader="javafml"
loaderVersion="[2,)"
license="https://github.com/noobanidus/Lootr/blob/1.16/LICENSE"

[[mods]]
    modId="lootr_gametest"
    version="1.0.0"
    displayName="Lootr Game Tests"
    description="Game tests for Lootr."

[[dependencies.lootr_gametest]]
    modId="lootr"
    type="required"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
