plugins {
    id 'net.neoforged.moddev'
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
}

dependencies {
    compileOnly(project(':common')) {
        transitive = false
    }
    //jarJar(implementation "dev.thomasglasser.sherdsapi:sherdsapi-neoforge-${minecraft_version}:${sherdsapi_version}")
    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:${rootProject.mixin_extras_version}"))
    implementation("io.github.llamalad7:mixinextras-neoforge:${rootProject.mixin_extras_version}")
}

publishMods {
    file = tasks.jar.archiveFile
    modLoaders.add("neoforge")

    var env = System.getenv()

    def gitRepo = getExecOutput(['git', 'remote', 'get-url', 'origin'])
    def gitCommit = getExecOutput(['git', 'log', '-n', '1', '--pretty=tformat:%h'])
    def gitPrevCommit = project.findProperty("git_previous_commit") ?: env["GIT_PREVIOUS_COMMIT"]

    var changelogText = ""

    if (gitCommit && gitPrevCommit) {
        changelogText += getExecOutput(['git', 'log', "--pretty=tformat:- %s [(%h)](${gitRepo}/commit/%h)", '' + gitPrevCommit + '..' + gitCommit])
    }

    // Limit the changelog to 500 characters
    changelogText = changelogText.take(500)

    if (project.hasProperty('curseforge_id_neoforge')) {
        curseforge('curseforgeNeoForge') {
            type = ALPHA

            projectSlug = "lootr"
            displayName = "lootr-neoforge-${rootProject.minecraft_version}-${rootProject.mod_version}"
            accessToken = project.findProperty("curse_auth")
            projectId = project.findProperty('curseforge_id_neoforge')
            announcementTitle = "Lootr ${rootProject.minecraft_version}-${rootProject.mod_version} for NeoForge on CurseForge"
            minecraftVersions.add(project.minecraft_version)
            changelog = changelogText
        }
    }

    if (project.hasProperty('modrinth_id_fabric')) {
        modrinth('modrinthNeoForge') {
            type = ALPHA
            displayName = "lootr-neoforge-${rootProject.minecraft_version}-${rootProject.mod_version}"
            accessToken = project.findProperty("modrinth_auth")
            projectId = project.findProperty('modrinth_id_neoforge')
            announcementTitle = "Lootr ${rootProject.minecraft_version}-${rootProject.mod_version} for NeoForge on Modrinth"
            minecraftVersions.add(project.minecraft_version)
            changelog = changelogText
        }
    }

    if (project.hasProperty("curse_discord_webhook")) {
        discord {
            webhookUrl = project.findProperty("curse_discord_webhook")
            username = "Lootr Update"
            content = "A new version of Lootr has been released!\n\n${changelogText.take(500)}"
        }
    }
}

neoForge {
    version = project.neoforge_version

    parchment {
        minecraftVersion = project.parchment_minecraft_version
        mappingsVersion = project.parchment_mappings_version
    }

    def atFile = project.file("src/main/resources/META-INF/accesstransformer_neoforge.cfg")
    if (atFile.exists()) {
        accessTransformers {
            from atFile
            publish atFile
        }
    }

    validateAccessTransformers.set(true)

    mods {
        // define mod <-> source bindings
        // these are used to tell the game which sources are for which mod
        // mostly optional in a single mod project
        // but multi mod projects should define one per mod
        "${mod_id}" {
            sourceSet(sourceSets.main)
            sourceSet(project.project(":common").sourceSets.main)
        }
    }

    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG

            gameDirectory = project.file('run')

            sourceSet = sourceSets.main
            loadedMods.set([mods."${mod_id}"])
        }

        client {
            client()
            //systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id

            if (project.hasProperty('mc_uuid')) {
                programArguments.add("--uuid=${project.findProperty('mc_uuid')}")
            }

            if (project.hasProperty('mc_username')) {
                programArguments.add("--username=${project.findProperty('mc_username')}")
            }

            if (project.hasProperty('mc_java_agent_path')) {
                jvmArgument("-javaagent:${project.findProperty('mc_java_agent_path')}")
            }
        }

        server {
            server()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        clientData {
            data()
            programArguments.addAll '--all', '--mod', 'lootr', '--existing', project.project(":common").file("src/main/resources").absolutePath, '--output', project.project(":common").file("src/generated/resources").absolutePath
        }
    }
}

tasks.named("compileJava", JavaCompile) {
    source(project.project(":common").sourceSets.main.allJava)
}

tasks.named("javadoc", Javadoc) {
    source(project.project(":common").sourceSets.main.allJava)
}

tasks.named("sourcesJar", Jar) {
    from(project.project(":common").sourceSets.main.allSource)
}

processResources {
    from project.project(":common").sourceSets.main.resources

    from(project(":common").sourceSets["generated"].resources) {
        exclude(".cache")
    }
}

publishing {
    tasks.publish.dependsOn build

    publications {
        mavenJava(MavenPublication) {

            artifactId project.archivesBaseName
            artifact jar
            artifact project.sourcesJar {
                archiveClassifier.set('sources')
            }

            pom {
                name = 'Lootr'
                description = 'Friendly loot for everyone.'
                url = 'https://github.com/LootrMinecraft/Lootr'

                scm {
                    connection = 'git:https://github.com/LootrMinecraft/Lootr.git'
                    developerConnection = 'git:https://github.com/LootrMinecraft/Lootr.git'
                    url = 'https://github.com/LootrMinecraft/Lootr'
                }

                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://opensource.org/licenses/MIT'
                    }
                }

                developers {
                    developer {
                        id = 'noobanidus'
                        name = 'Noobanidus'
                        email = 'noobanidus+spam@gmail.com'
                    }
                }
            }
        }
    }

    repositories {
        maven {
            url "file:///" + System.getenv("local_maven")
        }
    }
}

tasks.build.mustRunAfter tasks.clean
tasks.publish.mustRunAfter tasks.build
tasks.publishMods.mustRunAfter tasks.publish
tasks.buildAndRelease.dependsOn(tasks.clean, tasks.build, tasks.publish, tasks.publishMods)
