@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package noobanidus.mods.lootr.neoforge;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;