@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package noobanidus.mods.lootr.neoforge.mixin.integration.digsite_workshop;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;