package noobanidus.mods.lootr.common.api.interfaces.processor;

import net.minecraft.resources.Identifier;
import net.minecraft.world.entity.player.Player;

import java.util.UUID;

/*
  Team resolvers take a player and return a UUID.

  That UUID can either be the player's own UUID, or a UUID
  generated by some other method, but most not be null.

  Its resolver id can be pinned using the configuration,
  otherwise the highest priority resolver is used.

  Resolvers are only used if the teams option is enabled
  on the server.
 */
public interface ITeamResolver {
  UUID resolveServerPlayer(Player player);

  UUID resolveClientPlayer(Player player);

  Identifier resolverId();

  default int priority() {
    return 0;
  }
}